name: rave_flutter
description: A new Flutter plugin for making payment with Flutterwave's rave.
version: 0.0.8-alpha+1
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/rave_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.14.2
  http: ^0.12.0+2
  intl: ^0.16.0
  meta: ^1.1.7
  async: ^2.3.0
  dio: ^3.0.3
  get_it: ^3.0.1
  equatable: ^0.6.1
  tripledes: ^2.1.0
  webview_flutter: ^0.3.15+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.flutterwave.rave_flutter
    pluginClass: RaveFlutterPlugin

  assets:
    - assets/images/
