name: rave_flutter
description: A new Flutter plugin for Flutterwave's rave.
version: 0.0.1-alpha.1
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/rave_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.flutterwave.rave_flutter
    pluginClass: RaveFlutterPlugin
