name: rave_flutter
description: A new Flutter plugin for making payment with Flutterwave's rave.
version: 0.0.4-alpha
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/rave_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.14.0
  http: ^0.12.0+2
  intl: ^0.15.8
  meta: ^1.1.6
  async: ^2.1.0
  dio: ^2.1.16
  get_it: ^2.0.3
  equatable: ^0.5.1
  tripledes: ^2.1.0
  webview_flutter: ^0.3.13


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.flutterwave.rave_flutter
    pluginClass: RaveFlutterPlugin

  assets:
    - assets/images/
